import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { argmaxLabels, cleanPredSha, labelDtype, predPreimage, predSha256, predFromLogitsB64 } from './pred_hash.ts';
import { VisionBatch, type Rpc } from './vision_batch.ts';

// the same golden the Python worker checks (tests/py/test_pred_hash.py) — generated by tests/goldens/make_pred_golden.py
const G = JSON.parse(readFileSync(new URL('../../../tests/goldens/pred_sha256.json', import.meta.url), 'utf8')) as {
  cases: { name: string; labels: number[]; shape: number[]; dtype: string; sha256: string; preimage_hex: string }[];
  logits: { logits: (number | null)[]; shape: number[]; labels: number[]; labels_shape: number[]; sha256: string; logits_f32le_hex: string };
};
const hex = (u: Uint8Array) => Array.from(u, (x) => x.toString(16).padStart(2, '0')).join('');
const b64 = (u: Uint8Array) => btoa(String.fromCharCode(...u));

describe('pred_sha256 (moregpu.pred/1) — identical to moregpu_worker.vision.pred_hash', () => {
  for (const c of G.cases) {
    it(`golden ${c.name}`, async () => {
      expect(labelDtype(c.labels)).toBe(c.dtype);
      expect(hex(predPreimage(c.labels, c.shape))).toBe(c.preimage_hex);
      expect(await predSha256(c.labels, c.shape)).toBe(c.sha256);
      expect(await predSha256(Uint32Array.from(c.labels), c.shape)).toBe(c.sha256);
    });
  }
  it('golden logits → argmax labels (first max wins ties, NaN wins) → hash', async () => {
    const x = Float32Array.from(G.logits.logits.map((v) => (v === null ? NaN : v)));
    const bytes = new Uint8Array(x.buffer);
    expect(hex(bytes)).toBe(G.logits.logits_f32le_hex);
    const r = argmaxLabels(x, G.logits.shape);
    expect(Array.from(r.labels)).toEqual(G.logits.labels); expect(r.shape).toEqual(G.logits.labels_shape);
    expect(await predSha256(r.labels, r.shape)).toBe(G.logits.sha256);
    const p = await predFromLogitsB64(b64(bytes), G.logits.shape);
    expect(p).toEqual({ pred_sha256: G.logits.sha256, pred_shape: G.logits.labels_shape, pred_dtype: 'uint8' });
  });
  it('refusals', async () => {
    expect(() => labelDtype([70000])).toThrow(/65535/);
    expect(() => labelDtype([-1])).toThrow(/negative/);
    expect(() => labelDtype([0.5])).toThrow(/integer/);
    expect(() => predPreimage([1, 2, 3], [2, 2])).toThrow(/shape/);
    expect(() => argmaxLabels(new Float32Array(3), [3])).toThrow(/class axis/);
    expect(() => argmaxLabels(new Float32Array(5), [1, 2, 2])).toThrow(/shape/);
    expect(await predFromLogitsB64('AAAA', [1])).toBeNull();                        // not [B, C, ...]
    expect(await predFromLogitsB64(b64(new Uint8Array(12)), [1, 2, 2])).toBeNull(); // byte count ≠ shape
    expect(await predFromLogitsB64('', [1, 0, 3])).toBeNull();                      // no classes
  });
  it('cleanPredSha keeps only a 64-hex digest (worker replies are untrusted)', () => {
    expect(cleanPredSha('a'.repeat(64))).toBe('a'.repeat(64));
    for (const bad of ['A'.repeat(64), 'a'.repeat(63), '<script>', 7, null, undefined, { x: 1 }]) expect(cleanPredSha(bad)).toBeUndefined();
  });
  it('/vision/batch job records keep a valid worker pred_sha256 and drop a malformed one', async () => {
    const good = 'b'.repeat(64);
    const rpc: Rpc = async (_w, _op, p) => {
      const i = Number((p.ref as { uri: string }).uri.split('#')[1]);
      return { ok: true, data: { path: `/o/${i}.npy`, pred_sha256: i === 0 ? good : '../../etc', pred_dtype: i === 0 ? 'uint8' : '<img>' } };
    };
    const b = new VisionBatch('j', 'm', [0, 1].map((i) => ({ ref: { uri: `file://v#${i}` }, out: `c${i}` })), ['w'], rpc, {});
    await b.run();
    const r = [...b.results].sort((a, c) => a.index - c.index);
    expect(r[0]!.data!.pred_sha256).toBe(good); expect(r[0]!.data!.pred_dtype).toBe('uint8');
    expect(r[1]!.data!.pred_sha256).toBeNull(); expect(r[1]!.data!.pred_dtype).toBeNull();
  });
});
